version: '2'

services:
  harc:
    image: pillartechnology/cadbury:2.60.2
    environment:
      CI_URL: "http://pillartechnology.com:8080"
      THEME_COLOR: "blue-grey"
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - jenkins_home:/data/jenkins

volumes:
  jenkins_home:
